modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="dining"
version="1.0"
displayName="FB"
authors="sake"
description='''
Mobs can have a meal.
'''

[[mods]]
modId="friendly_mob_npc"
version="1.0.0"
displayName="Friendly_mobs"
authors="sake"
description='''
A custom NPC module.
'''

[[mods]]
modId="factions"
version="1.0.0"
displayName="Friendly_mobs"
authors="sake"
description='''
The mob factions and friendship module.
'''