modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="dining"
version="1.0"
displayName="dining"
displayURL="https://your-mod-url.com"
logoFile="logo.png"
authors="sake"
description='''
mobs can have a meal
'''

[[mods]]
modId="npc"
version="1.0.0"
displayName="npc"
authors="sake"
description='''
自定义NPC模组。
'''